#!/bash/sh
false || echo "Oops, fail"
# Oops, fail

true || echo "Will not be printed"
#

true && echo "Things went well"
# Things went well

false && echo "Will not be printed"
#

true ; echo "This will always run"
# This will always run

false ; echo "This will always run"
# This will always run

file=key
time=whatever

random(){
    whatever=23ii
    however=aston
    echo "?? $1"
    echo "?? $2"
}

mcd(){
mkdir -p "$1"
cd "$1"
echo "$#"
echo "$@"
echo "$?"
}
random
mcd ./newfile

echo "$#"
echo "$@"
echo "$?"
echo "$$"

